fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: renovate-config-validator-global
        name: renovate-config-validator-global
        language: system
        files: ^default\.json$
        entry: renovate-config-validator
        args: [--strict]

      - id: renovate-config-validator
        name: renovate-config-validator
        language: system
        types: [json]
        exclude: ^default\.json$
        entry: renovate-config-validator
        args: [--strict, --no-global]
